name: Docker

on:
  workflow_dispatch:
    inputs:
      versions:
        description: 'Version tag(s) for image, space separated'
        required: true
        default: 'latest'

env:
  IMAGE_NAME: go-tesla-go

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: 
          docker build .

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build --tag $IMAGE_NAME . 

      - name: Log into GitHub Container Registry
      # TODO: Create a PAT with `read:packages` and `write:packages` scopes and save it as an Actions secret `CR_PAT`
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/bogosj/go-tesla-go

          for i in ${{ github.event.inputs.versions }}
          do
              docker tag $IMAGE_NAME $IMAGE_ID:$i
              docker push $IMAGE_ID:$i
          done
